name: Build Claudix

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        run: git clone https://github.com/Haleclipse/Claudix.git

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.2.0

      - name: Build Claudix
        run: |
          npm install pnpm -g
          pnpm install
          pnpm build 
          pnpm package

      - name: Upload Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          path: *.vsix
      
      
